version: "3.8"

services:
    postgres-database:
        image: postgres:12.0
        container_name: tm-database
        restart: always
        env_file:
          - backend/.env
        ports: 
            - 5432:5432
    web:
        build: .
        command: bash -c "python3 manage.py makemigrations &&
                          python3 manage.py migrate &&
                          gunicorn -w 4 -b 0.0.0.0:8000 backend.wsgi:application"
        container_name: tm-backend
        volumes:
        - .:/code
        restart: always
        env_file:
            - backend/.env
        ports: 
            - 8000:8000
        depends_on: 
            - postgres-database
