version: "3.8"

services:
    PostgresDatabase:
        image: postgres:12.0
        env_file:
          - .env
        ports: 
            - 5432:5432
    DjangoLogic:
        image: aeroshev/task-manager-django:latest
        ports: 
            - 8000:8000
        depends_on: 
            - PostgresDatabase
