version: "3.8"

services:
    PostgresDatabase:
        image: postgres:12.0
        restart: always
        env_file:
          - .env
        ports: 
            - 5432:5432
    DjangoLogic:
        image: aeroshev/task-manager-backend:latest
        restart: always
        env_file:
            - .env
        ports: 
            - 8000:8000
        depends_on: 
            - PostgresDatabase
