version: "3.8"

services:
    postgres-database:
        image: postgres:12.0
        restart: always
        env_file:
          - apps/.env
        ports: 
            - 5432:5432
    django-logic:
        build: .
        restart: always
        env_file:
            - apps/.env
        ports: 
            - 8000:8000
        depends_on: 
            - postgres-database
